[package]
name = "serde-name"
version = "0.2.1"
description = "Extract the Serde name of structs and enums"
documentation = "https://docs.rs/serde-name"
repository = "https://github.com/zefchain/serde-reflection"
authors = ["Mathieu Baudet <mathieu.baudet@zefchain.com>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["data-structures", "serialization", "serde"]
categories = ["encoding", "development-tools"]
edition = "2021"
rust-version = "1.60"
exclude = [
    # Readme template that doesn't need to be included.
    "README.tpl",
]

[dependencies]
thiserror = "1.0.25"
serde = { version = "1.0.126", features = ["derive"] }

[dev-dependencies]
serde-reflection = { path = "../serde-reflection", version = "0.3.6" }
