[workspace]
members = [
    "serde-name",
    "serde-reflection",
    "serde-generate",
    "serde-generate-bin",
	"suite/*"
]
resolver = "2"

[profile.release]
debug = true
lto = 'thin'

[profile.bench]
debug = true
